Mayhem integration using Github Action
mayhemheroes/rav1e pull request #1
Opened 2022-04-26 02:27 UTC by Verylostpenguin

2022-04-27 12:08 UTC, nathanjackson requested changes
Thanks for your PR.

See my comments, there are a few things we need to have fixed before we can merge this.

2022-04-27 12:08 UTC, nathanjackson commented on Mayhemfile
> +  - cmd: /rav1e/fuzz/target/x86_64-unknown-linux-gnu/release/encode_decode
We need a few changes to your Mayhemfile:

- Remove your username from the project.
- No need to include duration.
- Please remove all but one `cmd` and rename the `target` field to reflect it. Mayhemfiles should be written for one target, but the multiple commands listed here would actually be for multiple targets.

For example, your Mayhemfile should look something like this:

```
project: rav1e
target: encode_decode

cmds:
  - cmd: /rav1e/fuzz/target/x86_64-unknown-linux-gnu/release/encode_decode
```

2022-04-29 01:49 UTC, Verylostpenguin commented on Mayhemfile
> +  - cmd: /rav1e/fuzz/target/x86_64-unknown-linux-gnu/release/encode_decode
I've deleted my username and the duration per the first two points.

I've split the commands in the mayhem files into multiple mayhemfiles that are now all called sequentially in mayhem.yml.

2022-05-03 17:53 UTC, nathanjackson requested changes
Hey @Verylostpenguin , sorry to take so long to get back with you. I merged your other PR, but found a few issues that I myself wasn't sure how to handle. So I had to fix a couple of things to better support multiple targets.

Your latest changes for this one also look good, but you need to prepend the `mayhemfiles` directory to the `--file` argument for each mcode-action. You should be able to see what I did to smoltcp to make this work.

2022-05-03 17:53 UTC, nathanjackson commented on .github/workflows/mayhem.yml
> +                --file ${{ env.ENCODE_MAYHEMFILE }}
I believe you need to prepend `mayhemfiles` to the file argument. See your other workflow: https://github.com/mayhemheroes/smoltcp/blob/master/.github/workflows/mayhem.yml

2022-05-04 23:38 UTC, Verylostpenguin commented on .github/workflows/mayhem.yml
> +                --file ${{ env.ENCODE_MAYHEMFILE }}
I've prepended the folder name and pushed the commit. Is there anything else that needs to be done?

2022-05-05 01:19 UTC, nathanjackson commented on .github/workflows/mayhem.yml
> +                --file ${{ env.ENCODE_MAYHEMFILE }}
Nope. Looks great 😄

2022-05-05 01:19 UTC, nathanjackson approved these changes
LGTM

2022-05-05 01:33 UTC, merged